name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Крок 1: Завантажуємо код з репозиторію
      - name: Checkout code
        uses: actions/checkout@v3

      # Крок 2: Налаштовуємо Node.js середовище
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Крок 3: Встановлюємо залежності
      - name: Install dependencies
        run: npm ci  # використовуємо "npm ci" для чистої установки залежностей

      # Крок 4: Розшифровуємо .env.production.gpg
      - name: Decrypt .env.production.gpg
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$SECRET_PASSPHRASE" \
            --output .env.production .env.production.gpg
        env:
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}

      # Крок 5: Створюємо білд
      - name: Build the project
        run: npm run build

      # Копіюємо index.html як 404.html (для правильної обробки роутів)
      - name: Copy index.html to 404.html
        run: cp dist/index.html dist/404.html

      # Крок 6: Деплой на gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # директорія, де знаходиться результат білду
          publish_branch: gh-pages
